---
title: "Syllabus"
author: "Daniel Fuller"
date: "August 28, 2017"
output:
      html_document:
        keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## HKR 6130 - Computer Applications for Physical Activity Measurement and Intervention

### Instructors
Dr. Daniel Fuller  
E-mail: dfuller@mun.ca  
Office: PE2023  

Dr.	Henry Luan  
E-mail: hluan@mun.ca  
Office: PE1007  

### Course Description
This course will introduce students to physical activity measurement using accelerometer devices including smartphones, smartwatches. I will also introduce students to measuring spatial location using Global Positioning Systems. The course will explore conceptual aspects of physical activity and spatial location measurement. Students will design, conduct, and analyse data for a small-scale intervention collecting accelerometer measured physical activity and GPS data. Students will learn programming in R and ArcGIS for spatial analysis methods. 

### Course Objectives
Upon completion of this course, students will be able to: 
*	Demonstrate an understanding of objective physical activity and spatial location measurement
*	Compare and contrast available technologies for physical activity measurement
*	Basic programming in R and QGIS
*	Design, conduct, and analyse data from a small-scale intervention using smart devices
